""" Test file for BaseGeometry class
===================================

Using "BaseGeometry"
"""

"""
Import
"""
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

    >>> bg = BaseGeometry()

    >>> bg.integer_validator("value", 0)
    Traceback (most recent call last):
    ...
    ValueError: value must be greater than 0

    >>> print(dir(bg))
    ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'area', 'integer_validator']

    >>> bg.integer_validator("value", 12)

    >>> bg.integer_validator("value", "hello")
    Traceback (most recent call last):
    ...
    TypeError: value must be an integer

    >>> bg.integer_validator("value", 5.43)
    Traceback (most recent call last):
    ...
    TypeError: value must be an integer

    >>> bg.integer_validator("value", [1, 2])
    Traceback (most recent call last):
    ...
    TypeError: value must be an integer

    >>> bg.integer_validator("value")
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

    >>> bg.integer_validator("value", 4, 5)
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() takes 3 positional arguments but 4 were given

    >>> bg.integer_validator("value", -6)
    Traceback (most recent call last):
    ...
    ValueError: value must be greater than 0

    >>> bg.integer_validator("value", None)
    Traceback (most recent call last):
    ...
    TypeError: value must be an integer

    >>> bg.integer_validator("value", True)
    Traceback (most recent call last):
    ...
    TypeError: value must be an integer

    >>> bg.integer_validator("value", {3, 4})
    Traceback (most recent call last):
    ...
    TypeError: value must be an integer

    >>> bg.area()
    Traceback (most recent call last):
    ...
    Exception: area() is not implemented

    >>> bg.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

    >>> bg.integer_validator("value", (3, ))
    Traceback (most recent call last):
    ...
    TypeError: value must be an integer

    >>> bg.integervalidator('myint', 12)
    Traceback (most recent call last):
    ...
    AttributeError: 'BaseGeometry' object has no attribute 'integervalidator'
